// src/routes/login/+page.svelte
<script lang="ts">
  import { signIn } from "@auth/sveltekit/client";

  import Discord from "$components/icons/discord.svelte";
</script>

<main class="w-full h-full flex items-center justify-center">
  <button
    class="p-2 border-[1px] border-black dark:border-gray-500 rounded-md inline-block"
    on:click={async () => await signIn("discord", { callbackUrl: decodeURIComponent(new URL(location.href).searchParams.get("redirect") ?? "/account") })}
  >
    <Discord class="w-6 h-6"/>
  </button>
</main>

// app/login/page.tsx
"use client";

import { signIn } from "next-auth/react";
import { FaDiscord } from "react-icons/fa6";

export default function Page()
{
  return (
    <main className="flex flex-row gap-2 items-center justify-center w-full h-full">
      <button className="p-2 border-[1px] border-black dark:border-gray-500 rounded-md"
              onClick={async () => await signIn("discord", { callbackUrl: "/" })}>
        <FaDiscord className="w-6 h-6"/>
      </button>
    </main>
  );
}
