// app/account/page.tsx
"use client";

import { signIn, signOut, useSession } from "next-auth/react";
import { FaDiscord } from "react-icons/fa6";
import { cn } from "@/lib/utils";
import React from "react";
import { IoTrashBin } from "react-icons/io5";
import { PiFileArchive } from "react-icons/pi";
import Link from "next/link";
import { metadata } from "@/app/layout";

interface ApiKey
{
  key: string;
  expiresAt: Date | null;
  createdAt: Date;
}

export default function Page ()
{
  const session = useSession();
  
  const deleteInput = React.useRef<HTMLInputElement>(null!);
  
  const [ keys, setKeys ] = React.useState<ApiKey[]>([]);
  
  React.useEffect(() =>
  {
    if ( session.data?.user?.role === "ADMIN" )
      fetch("/api", { method: "GET" })
      .then(async res =>
      {
        const json = await res.json();
        if ( json.success )
          setKeys(json.data);
        else alert(json.error);
      });
  }, []);
  
  return (
    <main className="flex p-2 w-full h-full items-center justify-center">
      {session.data?.user ? (
        <div className="rounded-lg bg-[#2c2c2c] p-2 shadow-md flex flex-col">
          <p>Logged in as <span
            className={cn("font-mono text-md bg-[#313131] rounded-md", session.data.user.role === "ADMIN" && "text-red-400")}>
            {session.data.user.email}
          </span></p>
          <button
            className="text-red-600 underline inline-block"
            onClick={async () => await signOut({ redirectTo: "/account" })}
          >Log Out
          </button>
          {session.data.user.role === "ADMIN" && (
            <div className="flex flex-col space-y-2">
              <div className="bg-[#313131] p-2 mt-2 flex flex-col font-mono text-xs whitespace-pre min-w-[350px]">
                <div className="w-full flex flex-row items-center">
                  <p>API Keys</p>
                  <div className="flex-grow"/>
                  <button onClick={async () =>
                  {
                    const res = await fetch("/api", { method: "POST" });
                    const json = await res.json();
                    if ( json.success )
                      setKeys([ ...keys, json.data ]);
                    else alert(json.error);
                  }}>
                    +
                  </button>
                </div>
                {"\n"}
                {JSON.stringify(keys, null, 2)}
              </div>
              <div
                className="bg-[#313131] p-2 mt-2 flex space-x-2 flex-row items-center font-mono text-xs whitespace-pre min-w-[350px]">
                <input
                  className="bg-transparent outline-none w-full"
                  ref={deleteInput}
                />
                <button
                  onClick={async () =>
                  {
                    const key = deleteInput.current.value;
                    const res = await fetch("/api", { method: "DELETE", body: JSON.stringify({ key }) });
                    const json = await res.json();
                    if ( json.success )
                    {
                      setKeys(keys.filter(k => k.key !== key));
                      deleteInput.current.value = "";
                    } else alert(json.error);
                  }}
                ><IoTrashBin/></button>
              </div>
              <div className="bg-[#313131] p-2 mt-2 flex flex-row font-mono text-xs whitespace-pre min-w-[350px]">
                <Link href="/files?archive">
                  <PiFileArchive
                    className="w-5 h-5"
                    title="Download archive"
                  />
                </Link>
              </div>
            </div>
          )}
        </div>
      ) : (
        <button className="p-2 border-[1px] border-black dark:border-gray-500 rounded-md inline-block"
                onClick={async () => await signIn("discord", { redirectTo: "/" })}>
          <FaDiscord className="w-6 h-6"/>
        </button>
      )}
    </main>
  );
}

// src/routes/account/+page.svelte
<script lang="ts">
  import type { Session } from "@auth/sveltekit";
  import { signOut } from "@auth/sveltekit/client";
  import type { ApiKey } from "$lib/types";

  import FileArchive from "$components/icons/file-archive.svelte";

  const requestAnApiKey = async () =>
  {
    const res = await fetch("/api", { method: "POST" });
    const { success, error, data } = await res.json();
    if ( success ) keys = [ ...keys, data ];
    else alert(error);
  };

  const deleteAnApiKey = async (keyValue: string) =>
  {
    const res = await fetch("/api", { method: "DELETE", body: JSON.stringify({ key: keyValue }) });
    const { success, error } = await res.json();
    if ( success )
    {
      keys = keys.filter((key) => key.key !== keyValue);
    } else alert(error);
  };

  export let data: { session: Session, keys: ApiKey[] };
  let { keys = [], session } = data;
</script>

<main class="flex p-2 w-full h-full items-center justify-center">
  <div class="rounded-lg bg-[#2c2c2c] p-2 shadow-md flex flex-col">
    <p>Logged in as
      <span
        data-admin={session.user.role === "ADMIN"}
        class="font-mono text-md bg-[#313131] rounded-md data-[admin=true]:text-red-400"
      >
        {session.user.email}
      </span>
    </p>
    <button
      class="text-red-600 underline inline-block"
      on:click={async () => await signOut({ callbackUrl: "/login" })}
    >
      Log Out
    </button>
    {#if session.user.role === "ADMIN"}
      <div class="flex flex-col space-y-2">
        <div class="bg-[#313131] p-2 mt-2 flex flex-col font-mono text-xs whitespace-pre min-w-[350px]">
          <div class="w-full flex flex-row items-center">
            <p>API Keys</p>
            <div class="flex-grow"/>
            <button on:click={requestAnApiKey} title="Create new API key">+</button>
          </div>
          {"-".repeat(44)}
          {#each keys as { key, expiresAt } (key)}
            <div class="flex flex-row items-center space-x-1">
              <button
                title="Click to copy"
                on:click={async () => navigator.clipboard.writeText(key)}
              >{key}</button>
              <div class="flex-grow"/>
              <p>{expiresAt?.toDateString() ?? "never"}</p>
              <button on:click={async () => await deleteAnApiKey(key)} title="Revoke">-</button>
            </div>
          {/each}
        </div>
        <div class="bg-[#313131] p-2 mt-2 flex flex-row font-mono text-xs whitespace-pre min-w-[350px]">
          <a href="/files?archive" title="Download archive">
            <FileArchive class="w-5 h-5"/>
          </a>
        </div>
      </div>
    {/if}
  </div>
</main>
