// src/routes/[filename]/+page.svelte
<script lang="ts">
  import type { File } from "@prisma/client";

  export let data: { file: File | null };
  let { file } = data;
  let mimeGroup = file?.mimeType.split("/")[0];
</script>

<main class="w-full h-full flex items-center justify-center">
  {#if file}
    {#if mimeGroup === "image"}
      <img
        src="/raw/{file.filename}"
        alt="{file.filename}"
        class="max-h-screen h-auto w-auto object-contain"
      >
    {:else if mimeGroup === "video"}
      <video
        controls
        class="max-h-screen h-auth w-auto object-contain"
      >
        <source src="/raw/{file.filename}" type="{file.mimeType}">
        <track src="/raw/{file.filename}" kind="captions">
        Your browser does not support the video tag.
      </video>
    {:else if mimeGroup === "audio"}
      <audio controls>
        <source src="/raw/{file.filename}" type="{file.mimeType}">
        Your browser does not support the audio tag.
      </audio>
    {:else if mimeGroup === "text"}
      <iframe
        src="/raw/{file.filename}"
        class="w-full h-full"
        title="{file.filename}"
      />
    {:else}
      <a
        href="/raw/{file.filename}"
        target="_blank"
        class="cursor-pointer"
      >Download ({file.mimeType})</a>
    {/if}
  {:else}
    <p class="text-center">File not found</p>
  {/if}
</main>

// app/[filename]/page.tsx
"use server";

import { Metadata, ResolvingMetadata } from "next";
import { File } from "@prisma/client";
import React from "react";
import Link from "next/link";
import { getFileRecordByFilename } from "@/data";

interface PageProps
{
  params: { filename: string };
  searchParams: { [key: string]: string | string[] | undefined };
}

export async function generateMetadata( props: PageProps, parent: ResolvingMetadata ): Promise<Metadata>
{
  const file: File | null = await getFileRecordByFilename(props.params.filename);
  const metadataBase: URL = (await parent).metadataBase!;
  
  if ( !file )
    return ({
      title: "File not found",
      openGraph: {
        type: "website",
        title: "File not found",
        description: "The requested file was not found on the server.",
      },
    });
  
  return ({
    metadataBase: metadataBase,
    title: file.filename,
    openGraph: {
      type: "website",
      title: file.filename,
      siteName: file.hash,
      description: "Meow :3",
      url: `/raw/${file.filename}`,
      images: /^image\//m.test(file.mimeType) ? [ { url: new URL(`/raw/${file.filename}`, metadataBase) } ] : undefined,
      audio: /^audio\//m.test(file.mimeType) ? [ { url: new URL(`/raw/${file.filename}`, metadataBase) } ] : undefined,
      videos: /^video\//m.test(file.mimeType) ? [ { url: new URL(`/raw/${file.filename}`, metadataBase) } ] : undefined,
    },
  });
}

export default async function Page( { params }: PageProps )
{
  const file: File | null = await getFileRecordByFilename(params.filename);
  
  return (
    <main className="w-full h-full items-center justify-center flex font-mono whitespace-pre">
      {file ? (
        (() =>
        {
          switch ( file.mimeType.split("/")[0] )
          {
            case "image":
              return <img
                src={`/raw/${params.filename}`}
                alt={params.filename}
                className="max-h-screen h-auth w-auto object-contain"
              />;
            case "audio":
              return <audio controls>
                <source src={`/raw/${file.filename}`} type={file.mimeType}/>
                Your browser does not support the audio element.
              </audio>;
            case "video":
              return <video
                src={`/raw/${file.filename}`}
                controls
                className="max-h-screen h-auth w-auto object-contain"
              />;
            case "text":
              return <iframe
                src={`/raw/${file.filename}`}
                className="h-screen w-screen"/>;
            default:
              return <Link href={`/raw/${file.filename}`} target="_blank" className="cursor-pointer">Download
                ({file.mimeType})</Link>;
          }
        })()
      ) : (
        <p className="text-center">File not found</p>
      )}
    </main>
  );
}
